# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

# Win32 and x64 are CMake-compatible solution platform names.
# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
  - RelWithDebInfo

#Cmake will autodetect the compiler, but we set the arch
before_build:
  - cmake -H. -BBuild -A%PLATFORM% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\carve_dev

# build with MSBuild
build:
  project: Build\carve.sln        # path to Visual Studio solution or project
  parallel: true                  # enable MSBuild parallel builds
  verbosity: normal               # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%

after_build:
  - 7z a CarveLib.zip %APPVEYOR_BUILD_FOLDER%\carve_dev\*

artifacts:
  - path: CarveLib.zip
    name: CarveLib