# version string format -- This will be overwritten later anyway
version: "{build}"

image:
  - Visual Studio 2019
  - Visual Studio 2015
  - Ubuntu

# Win32 and x64 are CMake-compatible solution platform names.
# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
  - RelWithDebInfo

for:
-
  matrix:
    only:
      - image: Ubuntu
  environment:
    CC: clang-9
    CXX: clang++-9
    CXXFLAGS: -stdlib=libc++
-
  matrix:
    only:
      - image: Visual Studio 201*

#Cmake will autodetect the compiler, but we set the arch
before_build:
  - cmake -H. -BBuild -A%PLATFORM% -DCMAKE_INSTALL_PREFIX=installdir

build_script:
  - cmd: cmake --build Build --target ALL_BUILD --config %CONFIGURATION% -- /nologo /verbosity:minimal /maxcpucount
  - cmd: cmake --build Build --target INSTALL --config %CONFIGURATION% -- /nologo /verbosity:minimal /maxcpucount

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - set BUILD_ARCHIVE=%APPVEYOR_PROJECT_NAME%-%CONFIGURATION%.zip
  - cmd: 7z a %BUILD_ARCHIVE% installdir

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%

artifacts:
  - path: '*.zip'
